site_name: CodeQuest 23 Game Documentation
nav:
    - Getting Started: index.md
    - Getting help: help.md
    - Game Objects:
      - Tank: game_objects/tank.md
      - Bullet: game_objects/bullet.md
      - Wall: game_objects/wall.md
      - Destructible-Wall: game_objects/destructibleWall.md
      - Powerup: game_objects/powerup.md
      - Boundary: game_objects/boundary.md
    - Game Logic:
      - Communication: game_logic/communication.md
      - Actions: game_logic/actions.md
      - Collisions: game_logic/collisions.md
      - Deleted_Objects: game_logic/deleted_objects.md
      - Map: game_logic/map.md
      - Types: game_logic/types.md
    - Your Bots and Submissions:
      - Requirements: bots_and_submissions/requirements.md
      - Starting your code: bots_and_submissions/starting_your_code.md
      - Running your code: bots_and_submissions/running_your_code.md
      - Submitting your code: bots_and_submissions/submitting_your_code.md
theme: readthedocs
