site_name: CodeQuest 23 Game Documentation
nav:
    - Getting Started: index.md
    - Game Objects:
      - Tank: tank.md
      - Bullet: bullet.md
      - Wall: wall.md
      - Destructible-Wall: destructibleWall.md
      - Powerup: powerup.md
      - Boundary: boundary.md
    - Game Logic:
      - Communication: communication.md
      - Actions: actions.md
      - Collisions: collisions.md
      - Events: events.md
      - Map: map.md
      - Types: types.md
theme: readthedocs
